[env]
_.python.venv = { path = ".venv" }

[tools]
dprint = "0.51.1"
hk = "1.36.0"
"github:sargunv/jvl" = "2026.02.17"
pkl = "0.30.2"
ruff = "0.15.2"
ty = "0.0.18"
uv = "0.10.6"

[hooks]
postinstall = ["uv sync", "hk install --mise"]

[tasks.generate]
description = "Generate an Anki deck"
run = "asl-anki-generator"

[tasks.check]
description = "Run lints and format checks"
run = "hk check"

[tasks.fix]
description = "Fix lints and formatting"
run = "hk fix"

[tasks.test]
description = "Run tests"
run = "pytest"

[settings]
experimental = true
pin = true
