[env]
_.python.venv = { path = ".venv" }

[tools]
uv = "latest"

[hooks]
postinstall = "uv sync"

[tasks.generate]
description = "Generate an Anki deck"
run = "python quick_run.py"

[tasks.server]
description = "Run the server"
run = "uvicorn server:app --reload"

[tasks.test]
description = "Run tests"
run = "pytest"
